stat_projet/stat_app/urls.py
from django.contrib import admin
from django.urls import include, path
from . import views

urlpatterns = [    
              
   path('login/', views.user_login, name='login'),
   path('logout/', views.user_logout, name='logout'),
   path('', views.index, name='app'),
   path('excel/', views.excel, name='excel'), 
   path('CSV/', views.csv, name='csv'),
  
   path('visualiser/', views.visualiser, name='visualiser'),
   path('visualiserChart/', views.visualiser_chart, name='visualiser_chart'),
   path('diagramme/', views.diagramme, name='diagramme'),
   path('parcourir/', views.parcourir_chart, name='parcourir_chart'),
   path('binomiale/', views.Binomiale, name='Binomiale'),
   path('bernoulli/', views.Bernoulli, name='Bernoulli'),
   path('normale/', views.Normale, name='Normale'),
   path('poisson/', views.Poisson, name='Poisson'),
   path('uniforme/', views.Uniforme, name='Uniforme'),
   path('exponentielle/', views.Exponentielle, name='Exponentielle'),

   path('calcules/', views.Calcules, name='Calcules'),
   path('inferentielles/', views.inferentielles, name='inferentielles'),
    path('test_traitement/', views.test_traitement, name='test_traitement'),
]

stat_projet/stat_projet/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings 
from django.conf.urls.static import static 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('stat_app.urls')),
]

stat_projet/stat_app/models.py
from django.db import models

# Create your models here.

stat_projet/stat_app/forms.py
from django import forms

class FileUploadForm(forms.Form):
    csv_file = forms.FileField(label='Fichier CSV', required=False)
    excel_file = forms.FileField(label='Fichier Excel', required=False)
    file = forms.FileField()

 

class BinomialForm(forms.Form):
    n = forms.IntegerField(label='Nombre d\'essais', initial=10, min_value=1)
    p = forms.FloatField(label='Probabilité de succès', initial=0.5, min_value=0, max_value=1)

class BernoulliForm(forms.Form):
    p = forms.FloatField(label='Probabilité de succès', initial=0.5, min_value=0, max_value=1)
    
class NormaleForm(forms.Form):
    mean = forms.FloatField(label='Moyenne')
    std_dev = forms.FloatField(label='Écart-type')
    

class PoissonForm(forms.Form):
    lambda_param = forms.FloatField(label='Lambda (λ)')
    
class UniformeForm(forms.Form):
    a = forms.FloatField(label='a',initial=2)
    b = forms.FloatField(label='b',initial=5)

class ExponentielleForm(forms.Form):
    beta = forms.FloatField(label='Beta (β)')

class TraitementForm(forms.Form):
    valeurs = forms.CharField(label='Liste de valeurs', widget=forms.TextInput(attrs={'placeholder': 'Entrez les valeurs séparées par des tirets (-) ou des virgules (,)'}))

class VisualizationForm(forms.Form):
    CHART_CHOICES = [
        ('histplot', 'Histogramme'),
        ('scatterplot', 'Nuage de points'),
        ('barplot', 'Diagramme à barres'),
        ('heatmap', 'Carte de chaleur'),
        ('lineplot', 'Graphique linéaire'),
        ('boxplot', 'Boîte à moustaches'),
        ('histogram', 'Histogramme'),
        ('kdeplot', 'Graphique KDE'),
        ('violinplot', 'Violon'),
        ('piechart', 'Diagramme circulaire'),
    ]

    chart_type = forms.ChoiceField(choices=CHART_CHOICES, label='Type de Diagramme', required=False)
    column_name_1 = forms.ChoiceField(choices=[], label='Nom de la colonne 1', required=False)
    column_name_2 = forms.ChoiceField(choices=[], label='Nom de la colonne 2', required=False)

stat_projet/stat_app/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.conf import settings
from django.shortcuts import render, redirect, HttpResponse
import pandas as pd 
import requests
from .forms import BinomialForm,FileUploadForm,ExponentielleForm,TraitementForm,UniformeForm,PoissonForm,NormaleForm
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from io import StringIO, BytesIO
import base64
import json
import plotly.express as px
import matplotlib
import plotly.graph_objs as go
from scipy.stats import binom
from django.http import JsonResponse
import plotly.io as pio
from .forms import BernoulliForm 
from scipy.stats import bernoulli,norm, t,expon, poisson,uniform
from scipy import stats
from unittest import result
matplotlib.use('Agg')
from statistics import mean, median, mode, variance, stdev
import plotly.figure_factory as ff

def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)  # Associe l'utilisateur à la session
            return redirect('app')  # Redirige vers une vue protégée
        else:
            messages.error(request, "Nom d'utilisateur ou mot de passe incorrect.")
    return render(request, 'login.html')
def user_logout(request):
    logout(request)
    return redirect('login')  # Redirige vers la page de connexion après déconnexion

@login_required
def index(request):
    return render(request, 'index.html')



def generate_chart(df, type_chart, col1, col2):
    buffer = BytesIO()

    if type_chart == 'Barplot':
        fig = px.bar(df, x=col1, y=col2)
        fig.update_layout(xaxis_title=col1, yaxis_title=col2, title='Bar Plot')
        return fig.to_json()

    elif type_chart == 'histogram':
        fig = px.histogram(df, x=col1)
        fig.update_layout(xaxis_title=col1, yaxis_title='Count', title='Histogram', barmode='overlay', bargap=0.1)
        return fig.to_json()

    elif type_chart == 'piechart':
        value_counts = df[col1].value_counts().reset_index()
        value_counts.columns = [col1, 'Count']
        fig = px.pie(value_counts, values='Count', names=col1, title='Pie Chart')
        return fig.to_json()


    elif type_chart == 'scatterplot':
        fig = px.scatter(df, x=col1, y=col2)
        fig.update_layout(xaxis_title=col1, yaxis_title=col2, title='Scatter Plot')
        return fig.to_json()

    elif type_chart == 'heatmap':
        df_encoded = df.copy()
        for column in df_encoded.columns:
            if df_encoded[column].dtype == 'object':
                df_encoded[column], _ = pd.factorize(df_encoded[column])
        fig = px.imshow(df_encoded.corr(), color_continuous_scale='Viridis')
        fig.update_layout(title='Heatmap')
        return fig.to_json()

    elif type_chart == 'lineplot':
       
        fig = px.line(df, x=col1, y=col2,markers=True)
        fig.update_layout(xaxis_title=col1, yaxis_title=col2, title='Line Plot')
        return fig.to_json()

        
    elif type_chart == 'boxplot':
        fig = px.box(df, x=col1)
        fig.update_layout(title='Box Plot')
        return fig.to_json()
        

    elif type_chart == 'violinplot':
        fig = px.violin(df, y=col1, box=True)
        fig.update_layout(yaxis_title=col1, title='Violin Plot')
        return fig.to_json()


  

    elif type_chart == 'kdeplot':
        data_to_plot = df[col1].replace([np.inf, -np.inf], np.nan).dropna()

        group_labels = ['distplot']  # This will be the label for the distribution
        # Generate the KDE plot with the histogram
        fig = ff.create_distplot([data_to_plot], group_labels, curve_type='kde', show_hist=True, histnorm='probability density')

        # Mise à jour de la disposition (layout) pour correspondre au style souhaité
        fig.update_layout(
            title="Kernel Density Estimation (KDE) Plot",
            yaxis_title="Density",
            xaxis_title=col1,
            showlegend=False,
            template='plotly_white'
        )

        # Update traces to match the desired style
        fig.update_traces(marker=dict(color='grey', line=dict(color='black', width=1.5)))

        fig_json = fig.to_json()

        return fig_json

@login_required
def csv(request):
    if request.method == 'POST':
        form = FileUploadForm(request.POST, request.FILES)
        if form.is_valid():
            fichier = request.FILES['file']
            if fichier.name.endswith('.csv'):
                # Traitez le fichier CSV
                data = pd.read_csv(fichier)
                df = pd.DataFrame(data)
                columns_choices = [(col, col) for col in df.columns]
                df_json = df.to_json()
                request.session['df_json'] = df_json

                return render(
                        request,
                        'visualiser_data.html',
                        {'form': form,  'df': df.to_html(classes='table table-bordered'), 'column_names': df.columns},
                )
            else:
                return HttpResponse("Seuls les fichiers CSV sont autorisés. Veuillez télécharger un fichier CSV.")
    else:
        form = FileUploadForm()

    return render(request, 'csv.html', {'form': form})
@login_required
def excel(request):
    if request.method == 'POST':
        form = FileUploadForm(request.POST, request.FILES)

        if form.is_valid():
            fichier = request.FILES['file']

            if fichier.name.endswith(('.xls', '.xlsx')):
                try:
                    data = pd.read_excel(fichier)
                    df = pd.DataFrame(data)
                    columns_choices = [(col, col) for col in df.columns]
                    df_json = df.to_json()
                    request.session['df_json']=df_json
                    return render(
                        request,
                        'visualiser_data.html',
                        {'form': form,  'df': df.to_html(classes='table table-bordered'), 'column_names': df.columns},
                    )
                except pd.errors.ParserError as e:
                    e = f"Erreur : Impossible de lire le fichier Excel. Assurez-vous que le fichier est au format Excel valide."
                    return render(request, 'excel.html', {'form': form, 'error_message': e})
            else:
                return HttpResponse("Seuls les fichiers Excel (.xls, .xlsx) sont autorisés. Veuillez télécharger un fichier Excel.")
    else:
        form = FileUploadForm()

    return render(request, 'excel.html', {'form': form})

def visualiser(request): 
    return render(request, 'visualiser_data.html')


@login_required
def visualiser_chart(request): 
    if request.method == 'POST':
        col1 = request.POST['col_name1']
        col2 = request.POST['col_name2']
        type_chart = request.POST['type_chart']
        df_json = request.session.get('df_json')
        
        df_json_io = StringIO(df_json)
        df = pd.read_json(df_json_io)
       
        if pd.api.types.is_string_dtype(df[col1]) and type_chart in ['kdeplot', 'violinplot', 'boxplot']:
            error_message = f"La colonne choisie est '{col1}'de type 'string', veuillez choisir une autre colonne."
            return render(request, 'diagramme.html', {'error_message': error_message})
        elif pd.api.types.is_string_dtype(df[col2]) and type_chart in ['Barplot', 'lineplot']:
            error_message = f"La deuxième colonne '{col2}' doit contenir des valeurs numériques. Veuillez choisir une autre colonne."
            return render(request, 'diagramme.html', {'error_message': error_message})
        elif type_chart == 'scatterplot':
            # Vérifier si l'une des colonnes n'est pas numérique
            if pd.api.types.is_string_dtype(df[col1]) or pd.api.types.is_string_dtype(df[col2]):
                # Préparer un message d'erreur en indiquant les noms des colonnes non numériques
                non_numeric_columns = [col for col in [col1, col2] if pd.api.types.is_string_dtype(df[col])]
                error_message = f"Les colonnes '{', '.join(non_numeric_columns)}' doivent être numériques. Veuillez choisir d'autres colonnes."
                return render(request, 'diagramme.html', {'error_message': error_message})

        elif type_chart=="Nothing":
            error_message = "Veuillez sélectionner un diagramme à afficher"
            return render(request, 'diagramme.html', {'error_message': error_message})
        
        chart = generate_chart(df, type_chart, col1, col2)
        return render(request, 'diagramme.html', {'chart': chart})
    
    return render(request, 'visualiser_data.html')

@login_required
def diagramme(request):
    return render(request, 'diagramme.html')



@login_required
def parcourir_chart(request):
    df = None
    columns_choices = None
    error_message = ""
    max_row = 0

    if 'df_json' in request.session:
        df_json = request.session['df_json']
        df = pd.read_json(StringIO(df_json))
        columns_choices = [col for col in df.columns]
        max_row = df.shape[0] - 1
        
    if request.method == 'POST':
        selected_columns = request.POST.getlist('selected_columns')
        parcourir_chart_type = request.POST.get('parcourir_chart')
        col_name1 = request.POST.get('col_name1')
        row_numb = request.POST.get('RowNumb')
        
        if selected_columns:
            df = df[selected_columns]

        if parcourir_chart_type == 'GroupBy':

stat_projet/stat_app/templates/csv.html
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>CSV</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
    
    <style>
        /* Styles généraux */
        body {
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            background-color: #f5f5f5;
            color: #333;
            margin: 0;
            padding: 0;
        }

        /* Conteneur principal */
        .container {
            width: 80%;
            margin: 0 auto;
            padding: 40px;
            background-color: #ffffff;
            border-radius: 10px;
            box-shadow: 0 4px 10px rgba(0, 0, 0, 0.1);
            margin-top: 30px;
        }

        /* Titre principal */
        h1 {
            text-align: center;
            color: #2c3e50;
            font-size: 2.5rem;
            margin-bottom: 40px;
        }

        /* Section contenant le formulaire */
        .section {
            background-color: #f9f9f9;
            margin-bottom: 40px;
            padding: 30px;
            border-radius: 8px;
            box-shadow: 0 2px 6px rgba(0, 0, 0, 0.1);
        }

        /* Titre de la section */
        .section h2 {
            font-size: 1.8rem;
            color: #2980b9;
            text-align: center;
            margin-bottom: 20px;
        }

        /* Conteneur du formulaire */
        .tools__container {
            display: flex;
            justify-content: center;
            align-items: center;
            flex-direction: column;
        }

        /* Style pour chaque bouton et champ de saisie */
        .tools__item {
            background-color: #ffffff;
            border: 2px solid #ddd;
            border-radius: 10px;
            padding: 25px;
            text-align: center;
            box-shadow: 0 2px 6px rgba(0, 0, 0, 0.1);
            margin-top: 20px;
            width: 100%;
            max-width: 500px;
            transition: transform 0.3s, background-color 0.3s ease;
        }

        .tools__item:hover {
            transform: translateY(-5px);
            background-color: #f1f1f1;
        }

        .tools__item a {
            color: #2980b9;
            text-decoration: none;
            font-size: 1.2rem;
            font-weight: 600;
            display: block;
            margin-top: 10px;
            transition: color 0.3s ease;
        }

        .tools__item a:hover {
            color: #3498db;
        }

        /* Style pour le bouton et le champ de fichier */
        input[type="file"] {
            padding: 20px;
            font-size: 1rem;
            background-color: #2980b9;
            border: 2px solid #2980b9;
            color: white;
            border-radius: 20px;
            width: 100%;
            margin-top: 20px;
            display: none;
        }

        /* Style du bouton "Upload" */
        #uploadButton {
            margin-top: 10px;
            padding: 15px;
            font-size: 1.2rem;
            background-color: #2980b9;
            border: 2px solid #2980b9;
            color: white;
            border-radius: 20px;
            width: 30%;
            cursor: pointer;
            transition: background-color 0.3s;
        }

        #uploadButton:hover {
            background-color: #3498db;
        }

        /* Style des boutons supplémentaires */
        button {
            margin-top: 20px;
            padding: 15px;
            font-size: 1rem;
            background-color: #2980b9;
            border: 2px solid #2980b9;
            color: white;
            border-radius: 20px;
            width: 100%;
            cursor: pointer;
        }

        button:hover {
            background-color: #3498db;
        }

        /* Conteneur pour les deux boutons */
        .button-container {
            display: flex;
            justify-content: space-between;
            gap: 10px;
        }

        /* Style des deux boutons */
        .button-container button {
            width: 48%; /* Pour avoir les deux boutons côte à côte */
        }

        /* Style spécifique au bouton "Retour" */
        .back-button {
            text-align: center;
            padding: 15px;
            font-size: 1.2rem;
            background-color: #2c3e50;
            color: white;
            border-radius: 20px;
            display: block;
            text-decoration: none;
            width: 100%;
            text-align: center;
        }

        .back-button:hover {
            background-color: #34495e;
        }
    </style>
</head>
<body>
    <nav style="background-color: #2c3e50; color: #ffffff; padding: 10px 20px; display: flex; justify-content: space-between; align-items: center;">
        <h3 style="margin: 0; color: #ffffff;">Statistiques et Tests</h3>
        <div>
            <a href="{% url 'app' %}" style="color: #ffffff; text-decoration: none; margin-right: 20px; font-weight: bold;">Home</a>
            {% if user.is_authenticated %}
                <a href="{% url 'logout' %}" style="color: #ffffff; text-decoration: none; font-weight: bold;">Déconnexion</a>
            {% else %}
                <a href="{% url 'login' %}" style="color: #ffffff; text-decoration: none; font-weight: bold;">Connexion</a>
            {% endif %}
        </div>
    </nav>
<div class="container">
    <!-- Partie 1 : Retour -->
   

    <!-- Partie 2 : Formulaire pour charger un fichier CSV -->
    <div class="section">
        <h2>Charger un fichier CSV</h2>
        <form method="post" enctype="multipart/form-data" action="{% url 'csv' %}" id="fileUploadForm">
            {% csrf_token %}
            <div class="tools__container">
                <button type="button" id="uploadButton">Télécharger</button>
                <input type="file" name="file" id="id_file" accept=".csv">
            </div>

            <div class="button-container">
                <!-- These buttons will appear when a file is selected -->
                <button type="submit" id="visualiserButton" style="display: none;">Visualiser</button>
                <button type="button" id="parcourirButton" style="display: none;">Parcourir</button>
            </div>
        </form>
    </div>


<script>
    // Show the file input when the "Upload" button is clicked
    document.getElementById('uploadButton').addEventListener('click', function () {
        document.getElementById('id_file').click(); // Open the file input dialog
    });

    document.getElementById('id_file').addEventListener('change', function () {
        // If a file is selected, both buttons ("Visualiser" and "Parcourir") will be displayed
        document.getElementById('visualiserButton').style.display = 'inline-block';
        document.getElementById('parcourirButton').style.display = 'inline-block';
    });

    // Handle the "Visualiser" button click
    document.getElementById('visualiserButton').addEventListener('click', function () {
        // Redirect to the visualisation page after clicking "Visualiser"
        window.location.href = "{% url 'visualiser_chart' %}";
    });

    // Handle the "Parcourir" button click
    document.getElementById('parcourirButton').addEventListener('click', function () {
        // Redirect to the "Parcourir" page after clicking "Parcourir"
        window.location.href = "{% url 'parcourir_chart' %}";
    });
</script>
</div>
</body>
</html>

stat_projet/stat_app/templates/diagramme.html
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Diagramme</title>
    <script src="https://cdn.plot.ly/plotly-latest.min.js"></script>
    <style>
        /* Style général pour le tableau et l'affichage du graphique */
        body {
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            background-color: #f4f7fc;
            margin: 0;
            padding: 0;
        }

        .container {
            width: 80%;
            margin: auto;
            padding: 30px;
            background-color: white;
            border-radius: 8px;
            box-shadow: 0 10px 30px rgba(0, 0, 0, 0.1);
        }

        /* Style du bouton de retour */
        .back-button {
            text-decoration: none;
            font-size: 1rem;
            color: #2980b9;
            padding: 10px 15px;
            border-radius: 5px;
            background-color: #f4f6f9;
            transition: background-color 0.3s;
        }

        .back-button:hover {
            background-color: #bdc3c7;
        }

        /* Style du graphique */
        #plotly-chart {
            margin-top: 30px;
        }

        /* Pour l'affichage des erreurs */
        .error-message {
            background-color: #f8d7da;
            color: #721c24;
            padding: 20px;
            margin-top: 20px;
            border-radius: 5px;
            text-align: center;
        }
    </style>
</head>

<body>
    <nav style="background-color: #2c3e50; color: #ffffff; padding: 10px 20px; display: flex; justify-content: space-between; align-items: center;">
        <h3 style="margin: 0; color: #ffffff;">Statistiques et Tests</h3>
        <div>
            <a href="{% url 'app' %}" style="color: #ffffff; text-decoration: none; margin-right: 20px; font-weight: bold;">Home</a>
            {% if user.is_authenticated %}
                <a href="{% url 'logout' %}" style="color: #ffffff; text-decoration: none; font-weight: bold;">Déconnexion</a>
            {% else %}
                <a href="{% url 'login' %}" style="color: #ffffff; text-decoration: none; font-weight: bold;">Connexion</a>
            {% endif %}
        </div>
    </nav>
    <div class="container">
        {% if chart %}
            <h2>AFFICHAGE :</h2>
            <div id="plotly-chart"></div>

            <script>
                var chartData = '{{ chart|safe }}'; 
                Plotly.newPlot('plotly-chart', JSON.parse(chartData), {});
            </script>

        {% else %}
            <div class="error-message">
                {% if error_message %}
                    <p>{{ error_message }}</p>
                {% else %}
                    <p>Pas de graphes disponible.</p>
                {% endif %}
                <button onclick="history.back()">TRY AGAIN</button>
            </div>
        {% endif %}
    </div>
</body>
</html>

stat_projet/stat_app/templates/excel.html
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <title>EXCEL</title>
    <style>
        /* Styles généraux */
        body {
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            background-color: #f5f5f5;
            color: #333;
            margin: 0;
            padding: 0;
        }

        /* Conteneur principal */
        .container {
            width: 80%;
            margin: 0 auto;
            padding: 40px;
            background-color: #ffffff;
            border-radius: 10px;
            box-shadow: 0 4px 10px rgba(0, 0, 0, 0.1);
            margin-top: 30px;
        }

        /* Titre principal */
        h1 {
            text-align: center;
            color: #2c3e50;
            font-size: 2.5rem;
            margin-bottom: 40px;
        }

        /* Section contenant le formulaire */
        .section {
            background-color: #f9f9f9;
            margin-bottom: 40px;
            padding: 30px;
            border-radius: 8px;
            box-shadow: 0 2px 6px rgba(0, 0, 0, 0.1);
        }

        /* Titre de la section */
        .section h2 {
            font-size: 1.8rem;
            color: #2980b9;
            text-align: center;
            margin-bottom: 20px;
        }

        /* Conteneur du formulaire */
        .tools__container {
            display: flex;
            justify-content: center;
            align-items: center;
            flex-direction: column;
        }

        /* Style pour chaque bouton et champ de saisie */
        .tools__item {
            background-color: #ffffff;
            border: 2px solid #ddd;
            border-radius: 10px;
            padding: 25px;
            text-align: center;
            box-shadow: 0 2px 6px rgba(0, 0, 0, 0.1);
            margin-top: 20px;
            width: 100%;
            max-width: 500px;
            transition: transform 0.3s, background-color 0.3s ease;
        }

        .tools__item:hover {
            transform: translateY(-5px);
            background-color: #f1f1f1;
        }

        .tools__item a {
            color: #2980b9;
            text-decoration: none;
            font-size: 1.2rem;
            font-weight: 600;
            display: block;
            margin-top: 10px;
            transition: color 0.3s ease;
        }

        .tools__item a:hover {
            color: #3498db;
        }

        /* Style pour le bouton et le champ de fichier */
        input[type="file"] {
            padding: 20px;
            font-size: 1rem;
            background-color: #2980b9;
            border: 2px solid #2980b9;
            color: white;
            border-radius: 20px;
            width: 100%;
            margin-top: 20px;
            display: none;
        }

        /* Style du bouton "Upload" */
        #uploadButton {
            margin-top: 10px;
            padding: 15px;
            font-size: 1.2rem;
            background-color: #2980b9;
            border: 2px solid #2980b9;
            color: white;
            border-radius: 20px;
            width: 30%;
            cursor: pointer;
            transition: background-color 0.3s;
        }

        #uploadButton:hover {
            background-color: #3498db;
        }

        /* Style des boutons supplémentaires */
        button {
            margin-top: 20px;
            padding: 15px;
            font-size: 1rem;
            background-color: #2980b9;
            border: 2px solid #2980b9;
            color: white;
            border-radius: 20px;
            width: 100%;
            cursor: pointer;
        }

        button:hover {
            background-color: #3498db;
        }

        /* Conteneur pour les deux boutons */
        .button-container {
            display: flex;
            justify-content: space-between;
            gap: 10px;
        }

        /* Style des deux boutons */
        .button-container button {
            width: 48%; /* Pour avoir les deux boutons côte à côte */
        }

        /* Style spécifique au bouton "Retour" */
        .back-button {
            text-align: center;
            padding: 15px;
            font-size: 1.2rem;
            background-color: #2c3e50;
            color: white;
            border-radius: 20px;
            display: block;
            text-decoration: none;
            width: 100%;
            text-align: center;
        }

        .back-button:hover {
            background-color: #34495e;
        }
    </style>
</head>
<body>
    <nav style="background-color: #2c3e50; color: #ffffff; padding: 10px 20px; display: flex; justify-content: space-between; align-items: center;">
        <h3 style="margin: 0; color: #ffffff;">Statistiques et Tests</h3>
        <div>
            <a href="{% url 'app' %}" style="color: #ffffff; text-decoration: none; margin-right: 20px; font-weight: bold;">Home</a>
            {% if user.is_authenticated %}
                <a href="{% url 'logout' %}" style="color: #ffffff; text-decoration: none; font-weight: bold;">Déconnexion</a>
            {% else %}
                <a href="{% url 'login' %}" style="color: #ffffff; text-decoration: none; font-weight: bold;">Connexion</a>
            {% endif %}
        </div>
    </nav>
<div class="container">
 
<br><br><br><br>
    <!-- Partie 2 : Formulaire pour charger un fichier CSV -->
    <div class="section">
        <h2>Fichier Excel</h2>
        <form method="post" enctype="multipart/form-data" action="{% url 'excel' %}" id="fileUploadForm">
            {% csrf_token %}
            <div class="tools__container">
                <button type="button" id="uploadButton">Upload</button>
                <input type="file" name="file" id="id_file" accept=".xls, .xlsx">
            </div>
        
            <div class="button-container">
                <!-- These buttons will appear when a file is selected -->
                <button type="submit" id="visualiserButton" style="display: none;">Visualiser</button>
                <button type="button" id="parcourirButton" style="display: none;">Parcourir</button>
            </div>
        </form>
    </div>


<script>
    // Show the file input when the "Upload" button is clicked
    document.getElementById('uploadButton').addEventListener('click', function () {
        document.getElementById('id_file').click(); // Open the file input dialog
    });

    document.getElementById('id_file').addEventListener('change', function () {
        // If a file is selected, both buttons ("Visualiser" and "Parcourir") will be displayed
        document.getElementById('visualiserButton').style.display = 'inline-block';
        document.getElementById('parcourirButton').style.display = 'inline-block';
    });

    // Handle the "Visualiser" button click
    document.getElementById('visualiserButton').addEventListener('click', function () {
        // Redirect to the visualisation page after clicking "Visualiser"
        window.location.href = "{% url 'visualiser_chart' %}";
    });

    // Handle the "Parcourir" button click
    document.getElementById('parcourirButton').addEventListener('click', function () {
        // Redirect to the "Parcourir" page after clicking "Parcourir"
        window.location.href = "{% url 'parcourir_chart' %}";
    });
</script>
</div>
</body>
</html>